apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-lab
  labels:
    app: k8s-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-lab
  template:
    metadata:
      labels:
        app: k8s-lab
    spec:
      containers:
        - name: k8s-lab
          image: alexfgomes/k8s-lab:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
